### ISSUE TITLE
BUG: Strul med uppkoppling i Google meet

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#436]
När vi igår hade styrelsemöte så kom inte Fanny, Johan och Diana in i mötet. Johan bytte sedan till noq-login och kom in.
Fanny och Diana sade att de var inloggade på noq men kunde be om insläpp.
Jag var inloggad med noq men såg ingen som ville bli insläppt.

**Comment by overath2** [comment]
Kan du kolla @inhyenoq ?

**Comment by inhyenoq** [comment]
Further investigation for this case is not available from my side because I do not have access to the meeting. Also, it is necessary to know how the user logged in on the browser and Google Meet when they attempted to enter the meeting room. 
But I can list some possible scenarios that can cause such an issue. 

> När vi igår hade styrelsemöte så kom inte Fanny, Johan och Diana in i mötet. Johan bytte sedan till noq-login och kom in.
- These can happen when he Google meeting setting forces non-members to get permission to enter.
https://github.com/user-attachments/assets/645e74b2-8e89-4bfb-a89f-00f07702ac3d
<img width="843" alt="Screenshot 2024-08-28 at 15 42 43" src="https://github.com/user-attachments/assets/bf88f0be-ca30-4224-9e9b-0623858ae97e">
    
If this was the cause, the solution is simple. Change the setting to "Öppna" and ask others to refresh the meeting page. They will be able to come in without wating.

> Fanny och Diana sade att de var inloggade på noq men kunde be om insläpp.
- When one faces this problem, I recommend to check the account icon on the top right corner. 
<img width="1005" alt="Screenshot 2024-08-28 at 16 12 15" src="https://github.com/user-attachments/assets/ebc16d78-ffa1-453c-8b7e-d84a20da2fb9">
- Google allows to login more than one account at the same time. Therefore, one can arrive the meeting page with a personal account even after loggedin to noQ account. The below video shows such a case.
https://github.com/user-attachments/assets/a29c8c88-5ad5-4a7e-b48a-af414d886c2f

> Jag var inloggad med noq men såg ingen som ville bli insläppt.
- That I haven't experienced and not know the reason. 

Hope this can help it.

**Comment by overath2** [comment]
Great. Can we save this to some faq?

**Comment by inhyenoq** [comment]
Added a link to the faq document at the end of the section about möte on the playbook.
https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.jun54sdhol6b

**Comment by FannyBacklin** [comment]
Sätter mig som wingmate och tycker den här är klar för nu, bra jobbat @inhyenoq!
